/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciospd2;

import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class WordCounterWindow extends javax.swing.JFrame {

    /**
     * Creates new form WordCounter
     */
    public WordCounterWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textInput = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        labelResultadoContador = new java.awt.Label();
        radioButtonOpcion1 = new javax.swing.JRadioButton();
        radioButtonOpcion2 = new javax.swing.JRadioButton();
        radioButtonOpcion3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        labelResultadoContador.setName(""); // NOI18N
        labelResultadoContador.setText("Cantidad de palabras: 50");

        radioButtonOpcion1.setText("Opción 1");
        radioButtonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonOpcion1ActionPerformed(evt);
            }
        });

        radioButtonOpcion2.setText("Opción 2");
        radioButtonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonOpcion2ActionPerformed(evt);
            }
        });

        radioButtonOpcion3.setText("Opción 3");
        radioButtonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonOpcion3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonOpcion3)
                    .addComponent(radioButtonOpcion2)
                    .addComponent(radioButtonOpcion1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(labelResultadoContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOK))
                .addGap(23, 23, 23)
                .addComponent(labelResultadoContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(radioButtonOpcion1)
                .addGap(18, 18, 18)
                .addComponent(radioButtonOpcion2)
                .addGap(18, 18, 18)
                .addComponent(radioButtonOpcion3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonOpcion1ActionPerformed
        // TODO add your handling code here:
        if (radioButtonOpcion1.isSelected()) {
            JOptionPane.showMessageDialog(this, "Seleccionó la opción 1");
        } else {
            JOptionPane.showMessageDialog(this, "Quitó la selección de la opción 1");
        }
        
    }//GEN-LAST:event_radioButtonOpcion1ActionPerformed

    private void radioButtonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonOpcion2ActionPerformed
        // TODO add your handling code here:
        if (radioButtonOpcion2.isSelected()) {
            JOptionPane.showMessageDialog(this, "Seleccionó la opción 2");
        } else {
            JOptionPane.showMessageDialog(this, "Quitó la selección de la opción 2");
        }
    }//GEN-LAST:event_radioButtonOpcion2ActionPerformed

    private void radioButtonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonOpcion3ActionPerformed
        // TODO add your handling code here:
        if (radioButtonOpcion3.isSelected()) {
            JOptionPane.showMessageDialog(this, "Seleccionó la opción 3");
        } else {
            JOptionPane.showMessageDialog(this, "Quitó la selección de la opción 3");
        }
    }//GEN-LAST:event_radioButtonOpcion3ActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        try {
            String inputText = textInput.getText();
            if (inputText.isEmpty())
                throw new Exception();
            int wordsCant = WordsCounter.wordsCounter(inputText);
            labelResultadoContador.setText("Cantidad de palabras: " + String.valueOf(wordsCant));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debes ingresar al menos una palabra.");
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordCounterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordCounterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordCounterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordCounterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordCounterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private java.awt.Label labelResultadoContador;
    private javax.swing.JRadioButton radioButtonOpcion1;
    private javax.swing.JRadioButton radioButtonOpcion2;
    private javax.swing.JRadioButton radioButtonOpcion3;
    private javax.swing.JTextField textInput;
    // End of variables declaration//GEN-END:variables
}
